language: php

notifications:
  email:
    recipients:

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 5.6
  - 7.0
  - 7.1

addons:
  postgresql: "9.3"

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_30_STABLE
    - MOODLE_BRANCH=MOODLE_31_STABLE
    - MOODLE_BRANCH=MOODLE_32_STABLE
    - MOODLE_BRANCH=MOODLE_33_STABLE
    - MOODLE_BRANCH=master

matrix:
  include:
    # Test older Moodles only with PHP 5.6
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_28_STABLE
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_29_STABLE
    # Test with MySQL
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master
    # Test with PHP 7.1
    - php: 7.1
      env: MOODLE_BRANCH=master

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ "$MOODLE_VERSION" = "master" ] || [ "$MOODLE_VERSION" -ge 32 ]; then export CI=2; else export CI=1; fi
  - echo $CI
  - phpenv config-rm xdebug.ini
  - cd ../..
  - git clone --mirror 'https://github.com/moodlehq/moodle-behat-extension.git' '/home/travis/.composer/cache/vcs/git-github.com-moodlehq-moodle-behat-extension.git/' || true
  - if [ "$CI" = 2 ]; then
      nvm install 8.9;
      nvm use 8.9;
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2;
    else
      composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
